export const data = [
  {
    id: 1,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 2,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 3,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 4,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 5,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 6,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 7,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 8,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 9,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
  {
    id: 10,
    image: require('../assets/images/image1.png'),
    title: 'Play a game',
    taskImage: require('../assets/images/task.png'),
    taskName: 'Running Now',
  },
];
